services:

  pulsecheck-api:

    build: .

    container_name: pulsecheck-api

    restart: unless-stopped

    ports:
      - "8000:8000"

  dashboard:

    build: ./dashboard

    container_name: pulsecheck-dashboard

    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - pulsecheck-api